--liquibase formatted sql

--changeset kahn_huseynov:11-create-promotions
CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(50) UNIQUE,
    discount_type VARCHAR(20) NOT NULL CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    discount_value DECIMAL(12,2) NOT NULL CHECK (discount_value > 0),
    minimum_order_amount DECIMAL(12,2) NOT NULL CHECK (minimum_order_amount >= 0),
    maximum_discount_amount DECIMAL(12,2) CHECK (maximum_discount_amount > 0),
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL,
    usage_limit INTEGER CHECK (usage_limit > 0),
    per_user_limit INTEGER CHECK (per_user_limit > 0),
    usage_count BIGINT NOT NULL DEFAULT 0 CHECK (usage_count >= 0),
    product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT,
    category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
    CHECK (ends_at > starts_at),
    CHECK (product_id IS NULL OR category_id IS NULL),
    CHECK (discount_type <> 'PERCENTAGE' OR discount_value <= 100),
    CHECK (usage_limit IS NULL OR usage_count <= usage_limit),
    CHECK (code IS NULL OR code ~ '^[A-Z0-9_-]+$')
);
CREATE TABLE promotion_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL REFERENCES promotions(id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,
    discount_amount DECIMAL(12,2) NOT NULL CHECK (discount_amount > 0)
);
CREATE INDEX idx_promotion_usage_user ON promotion_usages(promotion_id, user_id);
CREATE INDEX idx_promotions_automatic ON promotions(id) WHERE code IS NULL AND active = TRUE;
ALTER TABLE orders ADD COLUMN original_total_price DECIMAL(12,2);
ALTER TABLE orders ADD COLUMN discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN coupon_code VARCHAR(50);
ALTER TABLE orders ADD COLUMN promotion_name VARCHAR(150);
UPDATE orders SET original_total_price = total_price;
ALTER TABLE orders ALTER COLUMN original_total_price SET NOT NULL;
ALTER TABLE orders ADD CONSTRAINT ck_order_discount CHECK (
    discount_amount >= 0 AND total_price >= 0 AND original_total_price = total_price + discount_amount
);
